### ISSUE TITLE
Deep Copy Of Nodes

### ISSUE THREAD

**Issue by jonassode** [jonassode/gamejs#24]
Class: _tilemap_class
Method: .place
Row: 820

When background nodes are placed on the board the function _tilemap_class.place is used. 
But there is a problem with this function since it only copies the objects that are are default node objects. 

We need to have a deep copy that also copies game specific objects 

Exampel

a = tilemap._tile(...)
a.text = "ninja"
a.func = function(){ alert('my fucntion'); }

tilemap.place(1,2,a)
tilemap.background(1,2).func()
// this last row should work

I tired a recursive deep copy of all objects in the node but it gave me problems since there are lots of back-references in the Node ( to tilemap and such )

**Comment by jonassode** [comment]
When i wrote the function i thoguth that var tile = jQuery.extend(true, {}, original_tile); did a deep copy/clone but I don't think that is the correct behaviour.

I'ts that function call ( var tile = jQuery.extend(true, {}, original_tile) ) that needs to be replaced with something that work.

**Comment by oloake** [comment]
I'll have a look.

**Comment by jonassode** [comment]
This is invalid.
